# Generated by Django 3.1.3 on 2020-11-25 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pokemon',
        ),
    ]
