# Generated by Django 3.1.3 on 2020-11-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0003_pokemon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='lengendary',
            field=models.BooleanField(),
        ),
    ]
