# Generated by Django 3.1.3 on 2020-11-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeapp', '0004_auto_20201125_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='lengendary',
            field=models.CharField(max_length=255),
        ),
    ]
